spring:
  application:
    name: microservice-template
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
      discovery:
        enabled: true
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
      group:
        readiness:
          include: db,diskSpace
        liveness:
          include: ping
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    defaults:
      enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    internal-proxies: 10\.0\.0\.0/8|172\.16\.0\.0/12|192\.168\.0\.0/16

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.template.msa: ${LOGGING_LEVEL_COM_TEMPLATE_MSA:DEBUG}
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n} 